SET(CMAKE_SYSTEM_NAME AmigaOS4)
SET(AmigaOS4 1)
SET(CMAKE_SYSTEM_VERSION 1)
SET(CMAKE_SYSTEM_PROCESSOR ppc)
SET(CMAKE_C_COMPILER /usr/bin/ppc-amigaos-gcc)
SET(CMAKE_CXX_COMPILER /usr/bin/ppc-amigaos-g++)
SET(CXX_STANDARD_REQUIRED ON)
SET(CXX_STANDARD 14)
#SET(CMAKE_CXX_FLAGS "-mcrt=clib4 -mstrict-align -std=c++14 -O3 -DLOG_DISABLED=0 -DCAIRO_HAS_FC_FONT -D_GNU_SOURCE -D__USE_INLINE__ -g0 -gstabs1 -feliminate-unused-debug-symbols -Wfatal-errors -Wwrite-strings -Wno-ignored-attributes -Wno-unused-but-set-parameter -Wno-unused-parameter -Wno-cast-align -I/usr/ppc-amigaos/SDK/MUI_5.0/C/include/ -I/usr/ppc-amigaos/SDK/local/clib4/include")
SET(CMAKE_CXX_FLAGS "-mcrt=clib4 -mstrict-align -std=c++14 -O3 -DNDEBUG -DCAIRO_HAS_FC_FONT -D_GNU_SOURCE -D__USE_INLINE__ -pipe -g0 -gstabs1 -feliminate-unused-debug-symbols -Wwrite-strings -Wno-ignored-attributes -Wno-unused-but-set-parameter -Wno-unused-parameter -Wno-cast-align -I/usr/ppc-amigaos/SDK/MUI_5.0/C/include/ -I/usr/ppc-amigaos/SDK/local/clib4/include")
SET(CMAKE_CXX_FLAGS_RELEASE "")
SET(CMAKE_CXX_FLAGS_DEBUG "-Wno-ignored-attributes -Wno-unused-but-set-parameter -pipe")
SET(CMAKE_CXX_FLAGS_RELEASE_INIT "")
SET(CMAKE_C_FLAGS "-mcrt=clib4 -mstrict-align -O3 -DCAIRO_HAS_FC_FONT -D_GNU_SOURCE -D__USE_INLINE__ -pipe -Wno-ignored-attributes -Wno-cast-align -I/usr/ppc-amigaos/SDK/MUI_5.0/C/include/ -I/usr/ppc-amigaos/SDK/local/clib4/include")
SET(CMAKE_C_FLAGS_DEBUG "-Wno-ignored-attributes -Wwrite-strings ")
SET(CMAKE_MODULE_LINKER_FLAGS "-lpthread -athread=native")
SET(CMAKE_FIND_LIBRARY_SUFFIXES .a)
SET(ODISSEY_PLATFORM "AmigaOS4")
SET(AROS_SDK_DIR /usr/ppc-amigaos/SDK/local/clib4)
SET(CMAKE_FIND_ROOT_PATH /usr/ppc-amigaos/SDK/local/clib4)
SET(CMAKE_LIBRARY_PATH /usr/ppc-amigaos/SDK/local/clib4/lib)
SET(CMAKE_INCLUDE_PATH /usr/ppc-amigaos/SDK/local/clib4/include)
SET(SQLite3_LIBRARY /usr/ppc-amigaos/SDK/local/clib4/lib/sqlite/instdir/include)
SET(SQLite3_INCLUDE_DIR /usr/ppc-amigaos/SDK/local/common/include)
SET(NGHTTP2_INCLUDE_DIRS /usr/ppc-amigaos/SDK/local/common/include)
SET(HYPHEN_INCLUDE_DIR /usr/ppc-amigaos/SDK/local/common/include/hyphen)
SET(HarfBuzz_INCLUDE_DIRS /usr/ppc-amigaos/SDK/local/clib4/include/harfbuzz)
SET(CURL_INCLUDE_DIR /usr/ppc-amigaos/SDK/local/common/include/curl)
SET(OpenJPEG_INCLUDE_DIR /usr/ppc-amigaos/SDK/local/clib4/include/openjpeg-2.5)
SET(WebP_DEMUX_LIBRARY /usr/ppc-amigaos/SDK/local/clib4/lib/libwebpdemux.a)
SET(HarfBuzz_ICU_LIBRARY /usr/ppc-amigaos/SDK/local/clib4/lib/libharfbuzz-icu.a)
SET(Fontconfig_INCLUDE_DIR /usr/ppc-amigaos/SDK/local/common/include)
SET(ICU_I18N_LIBRARY /usr/ppc-amigaos/SDK/local/clib4/lib/libicui18n.a)
SET(ICU_DATA_LIBRARY /usr/ppc-amigaos/SDK/local/clib4/lib/libicudata.a)
SET(ICU_LIBRARY /usr/ppc-amigaos/SDK/local/clib4/lib/libicuuc.a)
SET(JPEG_LIBRARY /usr/ppc-amigaos/SDK/local/clib4/lib/libjpeg.a)
SET(LIBXML2_INCLUDE_DIR /usr/ppc-amigaos/SDK/local/clib4/include/libxml2)
SET(LIBXML2_LIBRARY "/usr/ppc-amigaos/SDK/local/clib4/lib/libxml2.a;/usr/ppc-amigaos/SDK/local/clib4/lib/liblzma.a")
SET(NGHTTP2_LIBRARIES /usr/ppc-amigaos/SDK/local/clib4/lib/libnghttp2.a)
SET(OPENSSL_CRYPTO_LIBRARY /usr/ppc-amigaos/SDK/local/clib4/lib/libcrypto.a)
SET(OPENSSL_SSL_LIBRARY /usr/ppc-amigaos/SDK/local/clib4/lib/libssl.a)
SET(ZLIB_LIBRARY /usr/ppc-amigaos/SDK/local/clib4/lib/libz.a)
SET(CAIRO_INCLUDE_DIRS /usr/ppc-amigaos/SDK/local/clib4/include/cairo)
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
